#!/usr/bin/env node
// Regenerates the self-contained Tampa_Bay_Crystal_Ball.html at the repo root by
// inlining public/styles.css, public/app.js (with embedded data), and replacing
// /api/data fetch with the literal data object. This is the artifact the
// scheduled refresh task (RECB-7) edits in place per the original epic spec.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const [html, css, appJs, dataRaw] = await Promise.all([
  readFile(path.join(root, 'public', 'index.html'), 'utf-8'),
  readFile(path.join(root, 'public', 'styles.css'), 'utf-8'),
  readFile(path.join(root, 'public', 'app.js'), 'utf-8'),
  readFile(path.join(root, 'data', 'dashboard.json'), 'utf-8')
]);

const data = JSON.parse(dataRaw);

const inlinedJs = appJs
  .replace(
    /const res = await fetch\('\/api\/data'\);[\s\S]*?data = await res\.json\(\);/,
    `data = __EMBEDDED_DATA__;`
  )
  .replace(/try\s*\{\s*data = __EMBEDDED_DATA__;\s*\}\s*catch[\s\S]*?return;\s*\}/, 'data = __EMBEDDED_DATA__;')
  .replace('__EMBEDDED_DATA__', JSON.stringify(data, null, 2));

let out = html
  .replace(
    /<link rel="stylesheet" href="\/styles\.css">/,
    `<style>\n${css}\n</style>`
  )
  .replace(
    /<script src="\/app\.js"><\/script>/,
    `<script>\n${inlinedJs}\n</script>`
  );

// Add a marker comment so the refresh task knows this is a generated artifact.
out = out.replace(
  '<head>',
  '<head>\n<!-- GENERATED by scripts/build-static.mjs from data/dashboard.json — do not hand-edit -->'
);

await writeFile(path.join(root, 'Tampa_Bay_Crystal_Ball.html'), out, 'utf-8');
console.log(`Built Tampa_Bay_Crystal_Ball.html (${(out.length / 1024).toFixed(1)} KB)`);
